### ISSUE TITLE
sudo pip install . resulting in an error

### ISSUE THREAD

**Issue by hkiyani** [siddhi-io/PySiddhi#13] opened 2018-04-26 08:38 UTC
**Description:**
I was trying to install pysidhi, but when i enter the command "sudo pip install" it results in the following error.
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-t0ar9M/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-D7qbKn/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-t0ar9M/

I am working on a ubuntu 16.04 machine. 
I would greatly appreciate any help here. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by AnuGayan** [comment] 2018-04-26 13:59
Could you please attach the full error log, so that we can identify the root cause of the problem.

**Comment by hkiyani** [comment] 2018-05-04 09:54
hello, sorry i didnt follow up sooner. 

>hkiyani@ubuntu:~/PySiddhi$ sudo pip install .
The directory '/home/hkiyani/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/hkiyani/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /home/hkiyani/PySiddhi
Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages (from PySiddhi4==1.0.1) (2.18.4)
Requirement already satisfied: pyjnius in /usr/local/lib/python2.7/dist-packages (from PySiddhi4==1.0.1) (1.1.1)
Requirement already satisfied: future in /usr/local/lib/python2.7/dist-packages (from PySiddhi4==1.0.1) (0.16.0)
Requirement already satisfied: enum34; python_version < "3.4" in /usr/local/lib/python2.7/dist-packages (from PySiddhi4==1.0.1) (1.1.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests->PySiddhi4==1.0.1) (2018.4.16)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests->PySiddhi4==1.0.1) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests->PySiddhi4==1.0.1) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests->PySiddhi4==1.0.1) (1.22)
Requirement already satisfied: six>=1.7.0 in /usr/local/lib/python2.7/dist-packages (from pyjnius->PySiddhi4==1.0.1) (1.11.0)
Requirement already satisfied: cython in /usr/lib/python2.7/dist-packages (from pyjnius->PySiddhi4==1.0.1) (0.23.4)
Installing collected packages: PySiddhi4
  Running setup.py install for PySiddhi4 ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-lE_nGs/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-hLpudG/install-record.txt --single-version-externally-managed --compile:
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    running install
    [INFO] Scanning for projects...
    [INFO]
    [INFO] ------------------------------------------------------------------------
    [INFO] Building siddhi-python-api-proxy-4 1.0.1
    [INFO] ------------------------------------------------------------------------
    [INFO]
    [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ siddhi-python-api-proxy-4 ---
    [INFO]
    [INFO] --- exec-maven-plugin:1.6.0:exec (clean-native-code) @ siddhi-python-api-proxy-4 ---
    rm -f liborg_wso2_siddhi_pythonapi_threadfix_pythreadfix.so
    [INFO]
    [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ siddhi-python-api-proxy-4 ---
    [WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
    [INFO] Copying 1 resource
    [INFO]
    [INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ siddhi-python-api-proxy-4 ---
    [INFO] Changes detected - recompiling the module!
    [WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
    [INFO] Compiling 18 source files to /tmp/pip-req-build-lE_nGs/__PySiddhi4Proxy/target/classes
    [WARNING] /tmp/pip-req-build-lE_nGs/__PySiddhi4Proxy/src/main/java/org/wso2/siddhi/pythonapi/DataWrapProxy.java:[20,52] com.sun.org.apache.xpath.internal.operations.Bool is internal proprietary API and may be removed in a future release
    [WARNING] /tmp/pip-req-build-lE_nGs/__PySiddhi4Proxy/src/main/java/org/wso2/siddhi/pythonapi/DataWrapProxy.java:[20,52] com.sun.org.apache.xpath.internal.operations.Bool is internal proprietary API and may be removed in a future release
    [WARNING] /tmp/pip-req-build-lE_nGs/__PySiddhi4Proxy/src/main/java/org/wso2/siddhi/pythonapi/DataWrapProxy.java:[20,52] com.sun.org.apache.xpath.internal.operations.Bool is internal proprietary API and may be removed in a future release
    [INFO]
    [INFO] --- exec-maven-plugin:1.6.0:exec (compile-native-code) @ siddhi-python-api-proxy-4 ---
    Building Target...
    g++ -shared -fPIC -c -I "/usr/lib/jvm/java-8-oracle/jre//include" -I "/usr/lib/jvm/java-8-oracle/jre//include/linux" -I "/usr/include/python" -o liborg_wso2_siddhi_pythonapi_threadfix_pythreadfix.so org_wso2_siddhi_pythonapi_threadfix_PyThreadFix.c
    org_wso2_siddhi_pythonapi_threadfix_PyThreadFix.c:19:17: fatal error: jni.h: No such file or directory
    compilation terminated.
    makefile:49: recipe for target 'liborg_wso2_siddhi_pythonapi_threadfix_pythreadfix.so' failed
    make: *** [liborg_wso2_siddhi_pythonapi_threadfix_pythreadfix.so] Error 1
    [ERROR] Command execution failed.
    org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:804)
        at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:751)
        at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:313)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 3.907 s
    [INFO] Finished at: 2018-05-04T02:47:23-07:00
    [INFO] Final Memory: 19M/185M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:exec (compile-native-code) on project siddhi-python-api-proxy-4: Command execution failed. Process exited with an error: 2 (Exit value: 2) -> [Help 1]
    [ERROR]
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR]
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-lE_nGs/setup.py", line 77, in <module>
        'Topic :: Software Development :: Libraries :: Java Libraries'
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-lE_nGs/setup.py", line 32, in run
        check_call("mvn clean install".split(), cwd="__PySiddhi4Proxy")  # shell=True should be skipped for linux
      File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['mvn', 'clean', 'install']' returned non-zero exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-lE_nGs/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-hLpudG/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-lE_nGs/

This is the error i got. If there is an error log file, im afraid i dont know how to locate it. I apologize.

**Comment by AnuGayan** [comment] 2018-05-05 04:40
It seems like you have set the JAVA_HOME path to **/usr/lib/jvm/java-8-oracle/jre** , Please confirm. If it is, Please set JAVA_HOME path as **/usr/lib/jvm/java-8-oracle** and see.

**Comment by hkiyani** [comment] 2018-05-07 06:40
Hi again, Thanks for the help. I think i managed to fix the JAVA_HOME issue. But now the install exits with the following error:

>   Building Target...
    g++ -shared -fPIC -c -I "/usr/lib/jvm/java-8-oracle/include" -I "/usr/lib/jvm/java-8-oracle/include/linux" -I "/usr/include/python" -o liborg_wso2_siddhi_pythonapi_threadfix_pythreadfix.so org_wso2_siddhi_pythonapi_threadfix_PyThreadFix.c
    In file included from /usr/include/boost/python/detail/prefix.hpp:13:0,
                     from /usr/include/boost/python/args.hpp:8,
                     from /usr/include/boost/python.hpp:11,
                     from org_wso2_siddhi_pythonapi_threadfix_PyThreadFix.c:22:
    /usr/include/boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory
    compilation terminated.
    makefile:49: recipe for target 'liborg_wso2_siddhi_pythonapi_threadfix_pythreadfix.so' failed
    make: *** [liborg_wso2_siddhi_pythonapi_threadfix_pythreadfix.so] Error 1
    [ERROR] Command execution failed.
    org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2)


Any ideas?
Thanks for your help!

**Comment by AnuGayan** [comment] 2018-05-09 06:36
Hi hkiyani, 

It seems like your pyconfig.h file is not in /usr/include/python folder but in some other folder, (/usr/include/python2.7 or /usr/include/python3.5). So inorder to change the included location, please change LINUX_PYTHON_PATH [in this file](https://github.com/wso2/PySiddhi/blob/master/__PySiddhi4Proxy/threadfix_c_code/makefile#L24) to where your pyconfig.h are, as an example if you are running python 2.7 it may be in /usr/include/python2.7. 

Please let us know if this solves the problem..

**Comment by AnuGayan** [comment] 2018-05-11 03:51
Hi @hkiyani, 

Were you able to install PySiddhi by following above approach? Please feel free to contact us if you need further assistance. 
Thanks.

**Comment by niveathika** [comment] 2018-11-04 15:43
Closing this issue as the question was answered. Please re-open if you need further assistance.

**Closed as completed by niveathika** 2018-11-04 15:43 UTC
